import {
	UnorderedListOutlined,
	CarOutlined,
	GiftOutlined,
	HomeOutlined,
	MobileOutlined,
	ShoppingCartOutlined,
	MoonOutlined,
	StarOutlined,
	CreditCardOutlined,
	BankOutlined,
	BookOutlined,
	HeartOutlined,
	DesktopOutlined,
	DatabaseOutlined,
	MessageOutlined,
	CalendarOutlined,
	FlagFilled,
	CheckOutlined,
	BulbOutlined,
	ExperimentOutlined,
	FundOutlined,
	InboxOutlined,
	CustomerServiceOutlined,
	RestOutlined,
	SettingOutlined,
} from '@ant-design/icons';
import BallOutlined from 'assets/icons/ball.svg';
import FishOutlined from 'assets/icons/fish.svg';
import AirPlaneOutlined from 'assets/icons/airplane.svg';

export const mapListToIcon = {
	UnorderedListOutlined: <UnorderedListOutlined/>,
	GiftOutlined: <GiftOutlined/>,
	CarOutlined: <CarOutlined/>,
	HomeOutlined: <HomeOutlined/>,
	MobileOutlined: <MobileOutlined />,
	ShoppingCartOutlined: <ShoppingCartOutlined />,
	MoonOutlined: <MoonOutlined />,
	StarOutlined: <StarOutlined />,
	CreditCardOutlined: <CreditCardOutlined />,
	BankOutlined: <BankOutlined />,
	BookOutlined: <BookOutlined />,
	HeartOutlined: <HeartOutlined />,
	DesktopOutlined:  <DesktopOutlined />,
	DatabaseOutlined: <DatabaseOutlined />,
	MessageOutlined: <MessageOutlined />,
	CalendarOutlined: <CalendarOutlined />,
	FlagFilled: <FlagFilled />,
	BallOutlined: <BallOutlined />,
	FishOutlined: <FishOutlined />,
	AirPlaneOutlined: <AirPlaneOutlined />,
	CheckOutlined: <CheckOutlined />,
	BulbOutlined: <BulbOutlined />,
	ExperimentOutlined: <ExperimentOutlined />,
	FundOutlined: <FundOutlined />,
	InboxOutlined: <InboxOutlined />,
	CustomerServiceOutlined: <CustomerServiceOutlined />,
	RestOutlined: <RestOutlined />,
	SettingOutlined: <SettingOutlined />,
} as const;
